config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }
  resources :portfolios do
    put :sort, on: :collection
  end
  get "about-me", to: "pages#about"
  get "contact", to: "pages#contact"
  resources :blogs do
    member do
      put :toggle_status
    end
  end
  root "pages#home"
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  scope :published, -> { where(:status => 1) }
  # Ex:- scope :active, lambda {where(:active => true)}

  validates_presence_of :title, :body
  # belongs_to :topic
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: { except: [:destroy, :new, :edit, :create, :update, :toggle_status] }, site_admin: :all

  def index
    if logged_in?(:site_admin)
      @blogs = Blog.page(params[:page]).per(5).order("created_at")
    else
      @blogs = Blog.published.page(params[:page]).per(5).order("created_at")
    end
    @page_title = "Blogs"
  end

  def show
    @page_title = @blog.title
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog, notice: "Your blog is now live"
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: "Blog was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: "Blog was successfully destroyed."
  end

  def toggle_status
    @blog.draft? ? @blog.published! : @blog.draft!
    redirect_to blogs_url, notice: "Post status has been updated."
  end

  private

  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title, blog %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>
  <% if logged_in?(:site_admin) %>
    <p>
      <%= link_to  blog.status, toggle_status_blog_path(blog), method: :put %> |
      <%= link_to 'Edit', edit_blog_path(blog) %> |
      <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
  <p><%= blog.body %></p>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :title, class: "form-control", placeholder: 'Title' %>
  </div>

  <div class="field form-group">
    <%= form.text_area :body, class: "form-control", rows: 15, placeholder: 'Content' %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %> 

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">
  <h2>Edit Blog</h2>

  <%= render 'form', blog: @blog %>
  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">
  <%= render @blogs %>
  <%= paginate @blogs %>
</div>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
  <h2>New Blog</h2>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">
  <h2><%= @blog.title %></h2>
  <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %>
  <p><%= @blog.body %></p>
</div>