config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }
  resources :portfolios do
    put :sort, on: :collection
  end
  get "about-me", to: "pages#about"
  get "contact", to: "pages#contact"
  resources :blogs do
    member do
      put :toggle_status
    end
  end
  root "pages#home"
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, reject_if: :reject_technologies, allow_destroy: true

  validates_presence_of :title, :subtitle, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  scope :angular_portfolio_item, -> { where(:subtitle => "Angular") }
  scope :by_position, -> { self.order("position asc") }

  after_initialize :set_position

  def reject_technologies(attributes)
    attributes["name"].blank?
  end

  def set_position
    self.position ||= (Portfolio.all.count + 1)
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  layout "portfolio"
  access all: [:show, :index], user: { except: [:destroy, :new, :edit, :create, :update, :sort] }, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def show
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def edit
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_item_params)

    if @portfolio_item.save
      redirect_to portfolios_url, notice: "Portfolio was successfully created."
    else
      render :new
    end
  end

  def sort
    params[:order].each do |portfolio|
      Portfolio.find(portfolio[:id]).update(position: portfolio[:position])
    end

    head :ok
  end

  def update
    if @portfolio_item.update(portfolio_item_params)
      redirect_to portfolios_url, notice: "Portfolio was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @portfolio_item.destroy
    redirect_to portfolios_url, notice: "Portfolio was successfully destroyed."
  end

  private

  def set_portfolio
    @portfolio_item = Portfolio.find(params[:id])
  end

  def portfolio_item_params
    params.require(:portfolio).permit(
      :title,
      :subtitle,
      :body,
      :main_image,
      :thumb_image,
      technologies_attributes: [:id, :name, :_destroy],
    )
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height, width)
    "https://via.placeholder.com/#{height}x#{width}/0000FF/808080"
  end

  def portfolio_img(img, type)
    if img
      img
    elsif type == "thumb"
      image_generator(350, 200)
    elsif type == "main"
      image_generator(600, 400)
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio_item, local: true) do |form| %>
  <% if portfolio_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio_item.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
        <% portfolio_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="field form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: "form-control" %>
      </div>

      <div class="field form-group">
        <%= form.label :main_image %>
        <%= form.file_field :main_image, class: "form-control-file" %>
      </div>

      <div class="field form-group">
        <%= form.label :thumb_image %>
        <%= form.file_field :thumb_image, class: "form-control-file" %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="field form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: "form-control", rows: 15 %>
      </div>
    </div>

    <hr>
    <div class="col-md-12">
      <h2>Technologies used</h2>
      <div class="field form-group">
        <%= form.fields_for :technologies do |tech_form| %>
          <%= render 'technology_fields', f: tech_form %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'Add Technology', form, :technologies %>
        </div>
      </div>

      <div class="actions">
        <%= form.submit class: "btn btn-primary btn-block" %>
      </div>
    </div>
  </div>

<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4 card-wrapper" data-id="<%= portfolio_item.id %>">
  <div class="card mb-4 shadow-sm">
    <%= image_tag portfolio_img(portfolio_item.thumb_image.url, 'thumb'), class: "bd-placeholder-img card-img-top"  %>
    <div class="card-body">
      <h6 class="card-text"><%= link_to portfolio_item.title, portfolio_path(portfolio_item) %></h6>
      <p class="card-text"><%= portfolio_item.subtitle %></p>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= link_to_remove_association "Remove technology", f %>
</div>

app/views/portfolios/edit.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <h2>Editing Portfolio</h2>
    <%= render 'form', portfolio_item: @portfolio_item %>

    <%= link_to 'Show', @portfolio_item %> |
    <%= link_to 'Back', portfolios_path %>
  </div>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <%= link_to 'New Portfolio', new_portfolio_path if logged_in?(:site_admin) %>
    <div class="row" id="<%= 'sortable' if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <h2>Create a new Portfolio</h2>
    <%= render 'form', portfolio_item: @portfolio_item %>
  </div>
</div>

app/views/portfolios/show.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <%= image_tag portfolio_img(@portfolio_item.main_image.url, 'main'), width: '100%' %>
      </div>
      <div class="col-md-5">
        <h3><%= @portfolio_item.title %></h3>
        <hr>
        <p><em><%= @portfolio_item.subtitle %></em></p>
        <p><%= @portfolio_item.body %></p>
        <hr>
        <h4>Technologies used:</h4>
        <% @portfolio_item.technologies.each do |tech| %>
          <p><%= tech.name %></p>
        <% end %>

        <br>
        <% if logged_in?(:site_admin) %>
          <%= link_to 'Edit', edit_portfolio_path(@portfolio_item), class: 'btn btn-warning'  %>
          <%= link_to 'Delete', portfolio_path(@portfolio_item), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
        <% end %>
      </div>
    </div>
  </div>
</div>