config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }
  resources :portfolios do
    put :sort, on: :collection
  end
  get "about-me", to: "pages#about"
  get "contact", to: "pages#contact"
  resources :blogs do
    member do
      put :toggle_status
    end
  end
  root "pages#home"
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner footer-text">
    <p>&copy; <%= Time.now.strftime('%Y') %> | <strong><a href="/">Blessing Mbonu</a></strong> All rights reserved</p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Blessing Mbonu</h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper("nav-link", "span") %>
      <%= login_helper('nav-link') %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>&copy; <%= Time.now.strftime('%Y') %> | <strong><a href="/">Blessing Mbonu</a></strong> All rights reserved</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_header.html.erb
<div class="blog-header">
  <h1 class="blog-title">My Blog</h1>
  <p class="lead blog-description">My official blog site.</p>
  <%= link_to 'Write a new blog', new_blog_path if logged_in?(:site_admin) %>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="blog-nav">
      <%= nav_helper("blog-nav-item", "span") %>
      <%= login_helper('blog-nav-item') %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-4 col-sm-offset-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled">
      <li class="social-links"><a href="https://github.com/Nkemjiks"><i class="fab fa-github"></i></a></li>
      <li class="social-links"><a href="https://twitter.com/mbonunkemjika"><i class="fab fa-twitter"></i></a></li>
      <li class="social-links"><a href="https://www.facebook.com/MbonuB"><i class="fab fa-facebook"></i></a></li>
    </ol>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="<%= location %>">
  <%= link_to "Home", root_path %><br />
  <%= link_to "About", about_me_path %><br />
  <%= link_to "Contact me", contact_path %><br />
  <%= link_to "Blogs", blogs_path %><br />
  <%= link_to "Portfolio", portfolios_path %><br />
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to  "View all portfolio items", portfolios_path %> |
      <a href="#">Back to top</a>
    </p>
    <p>&copy; <%= Time.now.strftime('%Y') %> | <strong><a href="/">Blessing Mbonu</a></strong> All rights reserved</p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>My Portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
    <p>
      <%= link_to  "Find out more about me", about_me_path, class: "btn btn-primary my-2" %>
      <%= link_to  "My Blogs", blogs_path, class: "btn btn-secondary my-2" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_navbar.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">A list of projects I have built over time. It consists of frontend apps, apis and fullstack application</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper("text-white", "li") %>
            <li><%= login_helper("text-white") %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Blessing Mbonu</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>